#!/bin/bash

set -e

if ! command -v tflint &> /dev/null
then
  curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E -m 1 "https://.+?_linux_amd64.zip")" > tflint.zip \
    && unzip tflint.zip \
    && rm tflint.zip \
    && sudo mv tflint /usr/bin/
fi
