name: terraform-validate
on: [push]
jobs:
  validate-terraform-layers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make validate
  ensure-correct-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: terraform fmt -check -recursive -diff
