name: terraform-validate
on: [push]
jobs:
  validate-terraform-layers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # TODO: Install Terraform
      # TODO: Install Make
      - run: make validate
